executable_path = '/usr/local/bin/chromedriver'
craig_tor_all = 'https://toronto.craigslist.org/search/apa?bundleDuplicates=1&availabilityMode=0&sale_date=all+dates'
craig_tor_posted_today = 'https://toronto.craigslist.org/search/apa?postedToday=1&bundleDuplicates=1&availabilityMode=0&sale_date=all+dates'
geocode_api='https://maps.googleapis.com/maps/api/geocode/json'
reverse_geocode_api='https://maps.googleapis.com/maps/api/geocode/json'
